# New Select Method

This page demonstrates how to select using the bracket notation using `NWIS.__getitem__()`

In [1]:
import hydrofunctions as hf
print(hf.__version__)

0.1.8dev

In [2]:
test = hf.NWIS('01542500,01585200', 'iv', period='P30D', file='test2.parquet')
test

Reading data from test2.parquet

USGS:01542500: WB Susquehanna River at Karthaus, PA
    00010: <15 * Minutes>  Temperature, water, degrees Celsius
    00060: <15 * Minutes>  Discharge, cubic feet per second
    00065: <15 * Minutes>  Gage height, feet
    00095: <15 * Minutes>  Specific conductance, water, unfiltered, microsiemens per centimeter at 25 degrees Celsius
    00300: <15 * Minutes>  Dissolved oxygen, water, unfiltered, milligrams per liter
    00400: <15 * Minutes>  pH, water, unfiltered, field, standard units
USGS:01585200: WEST BRANCH HERRING RUN AT IDLEWYLDE, MD
    00060: <5 * Minutes>  Discharge, cubic feet per second
    00065: <5 * Minutes>  Gage height, feet
Start: 2020-05-10 21:50:00+00:00
End:   2020-06-09 21:30:00+00:00

In [5]:
test['q'].tail()

subscript: q
 selectors: ['q']
args: ['q']
item: q

,USGS:01542500:00060:00000,USGS:01585200:00060:00000
datetimeUTC,,
2020-06-09 21:10:00+00:00,1033.333333,1.05
2020-06-09 21:15:00+00:00,1030.000000,1.05
2020-06-09 21:20:00+00:00,1030.000000,1.05
2020-06-09 21:25:00+00:00,1030.000000,1.05
2020-06-09 21:30:00+00:00,1030.000000,1.05

In [6]:
flags = test['flags']
flags.head()

subscript: flags
 selectors: ['flags']
args: ['flags']
item: flags

,USGS:01542500:00010:00000_qualifiers,USGS:01542500:00060:00000_qualifiers,USGS:01542500:00065:00000_qualifiers,USGS:01542500:00095:00000_qualifiers,USGS:01542500:00300:00000_qualifiers,USGS:01542500:00400:00000_qualifiers,USGS:01585200:00060:00000_qualifiers,USGS:01585200:00065:00000_qualifiers
datetimeUTC,,,,,,,,
2020-05-10 21:50:00+00:00,hf.upsampled,hf.upsampled,hf.upsampled,hf.upsampled,hf.upsampled,hf.upsampled,P,P
2020-05-10 21:55:00+00:00,hf.upsampled,hf.upsampled,hf.upsampled,hf.upsampled,hf.upsampled,hf.upsampled,P,P
2020-05-10 22:00:00+00:00,A,P,P,A,A,hf.upsampled,P,P
2020-05-10 22:05:00+00:00,hf.upsampled,hf.upsampled,hf.upsampled,hf.upsampled,hf.upsampled,hf.upsampled,P,P
2020-05-10 22:10:00+00:00,hf.upsampled,hf.upsampled,hf.upsampled,hf.upsampled,hf.upsampled,hf.upsampled,P,P

In [7]:
test['01585200'].head()

subscript: 01585200
 selectors: ['01585200']
args: ['01585200']
item: 01585200

,USGS:01585200:00060:00000,USGS:01585200:00065:00000
datetimeUTC,,
2020-05-10 21:50:00+00:00,2.05,1.19
2020-05-10 21:55:00+00:00,2.13,1.20
2020-05-10 22:00:00+00:00,2.05,1.19
2020-05-10 22:05:00+00:00,2.05,1.19
2020-05-10 22:10:00+00:00,2.13,1.20

In [8]:
# Buggy!  The system only accepts one selector right now.
# I think the issue is that getitem can only accept one arg, a string.
test['01542500','q']

AttributeError: 'tuple' object has no attribute 'split'

In [9]:
# The one selector can be a string that we separate into arguments!
test['01542500, q']

subscript: 01542500, q
 selectors: ['01542500', 'q']
args: ['01542500', 'q']
item: 01542500
item: q

                           USGS:01542500:00060:00000
datetimeUTC
2020-05-10 21:50:00+00:00                        NaN
2020-05-10 21:55:00+00:00                        NaN
2020-05-10 22:00:00+00:00                3380.000000
2020-05-10 22:05:00+00:00                3380.000000
2020-05-10 22:10:00+00:00                3380.000000
2020-05-10 22:15:00+00:00                3380.000000
2020-05-10 22:20:00+00:00                3380.000000
2020-05-10 22:25:00+00:00                3380.000000
2020-05-10 22:30:00+00:00                3380.000000
2020-05-10 22:35:00+00:00                3373.333333
2020-05-10 22:40:00+00:00                3366.666667
2020-05-10 22:45:00+00:00                3360.000000
2020-05-10 22:50:00+00:00                3360.000000
2020-05-10 22:55:00+00:00                3360.000000
2020-05-10 23:00:00+00:00                3360.000000
2020-05-10 23:05:00+00:00                3353.333333
2020-05-10 23:10:00+00:00                3346.666667
2020-05-10 23:15:00+00:00                3340.000000
2020-05-10 23:20:00+00:00                3333.333333
2020-05-10 23:25:00+00:00                3326.666667
2020-05-10 23:30:00+00:00                3320.000000
2020-05-10 23:35:00+00:00                3333.333333
2020-05-10 23:40:00+00:00                3346.666667
2020-05-10 23:45:00+00:00                3360.000000
2020-05-10 23:50:00+00:00                3366.666667
2020-05-10 23:55:00+00:00                3373.333333
2020-05-11 00:00:00+00:00                3380.000000
2020-05-11 00:05:00+00:00                3373.333333
2020-05-11 00:10:00+00:00                3366.666667
2020-05-11 00:15:00+00:00                3360.000000
...                                              ...
2020-06-09 19:05:00+00:00                1040.000000
2020-06-09 19:10:00+00:00                1040.000000
2020-06-09 19:15:00+00:00                1040.000000
2020-06-09 19:20:00+00:00                1040.000000
2020-06-09 19:25:00+00:00                1040.000000
2020-06-09 19:30:00+00:00                1040.000000
2020-06-09 19:35:00+00:00                1040.000000
2020-06-09 19:40:00+00:00                1040.000000
2020-06-09 19:45:00+00:00                1040.000000
2020-06-09 19:50:00+00:00                1040.000000
2020-06-09 19:55:00+00:00                1040.000000
2020-06-09 20:00:00+00:00                1040.000000
2020-06-09 20:05:00+00:00                1040.000000
2020-06-09 20:10:00+00:00                1040.000000
2020-06-09 20:15:00+00:00                1040.000000
2020-06-09 20:20:00+00:00                1040.000000
2020-06-09 20:25:00+00:00                1040.000000
2020-06-09 20:30:00+00:00                1040.000000
2020-06-09 20:35:00+00:00                1036.666667
2020-06-09 20:40:00+00:00                1033.333333
2020-06-09 20:45:00+00:00                1030.000000
2020-06-09 20:50:00+00:00                1033.333333
2020-06-09 20:55:00+00:00                1036.666667
2020-06-09 21:00:00+00:00                1040.000000
2020-06-09 21:05:00+00:00                1036.666667
2020-06-09 21:10:00+00:00                1033.333333
2020-06-09 21:15:00+00:00                1030.000000
2020-06-09 21:20:00+00:00                1030.000000
2020-06-09 21:25:00+00:00                1030.000000
2020-06-09 21:30:00+00:00                1030.000000

[8637 rows x 1 columns]

In [10]:
test.df['USGS:01542500:00010:00000'].head()

datetimeUTC
2020-05-10 21:50:00+00:00    NaN
2020-05-10 21:55:00+00:00    NaN
2020-05-10 22:00:00+00:00    9.2
2020-05-10 22:05:00+00:00    9.2
2020-05-10 22:10:00+00:00    9.2
Name: USGS:01542500:00010:00000, dtype: float64